### ISSUE TITLE
Add Field without div's

### ISSUE THREAD

**Issue by Lovntola** [fields-and-filters/fields-and-filters#2]
How can i add `#{field_id,article_id}` or `#{field_id}` in a content without any div's or formats around?
I need only the value in the source code. I have tried to create a own /plugins/fieldsandfilterstypes/input/tmpl/field/ my.php but if i remove all `<div>` there are many space around the value.  
Or is ther a soulution to add dies Values from the Fields in a JSON-LD script?

Thx for this great extention.
Bernd

**Comment by tkulka** [comment]
Hello Bernd,
sorry for late reply.

You can overwrite or create new layout for fields, filters, static.

**For Filters (e.g. List)**

Overwrite:
1. Copy file: plugins/fieldsandfilterstypes/list/tmpl/filter/default.php 
2. To: templates/your_template/html/plg_fieldsandfilterstypes_list/filter/default.php

New:
1. Copy file: plugins/fieldsandfilterstypes/list/tmpl/filter/default.php 
2. Rename file, eg.: plugins/fieldsandfilterstypes/list/tmpl/filter/new.php
3. Go to PA -> Components -> Fields and Filters -> Fields -> your_filter_name -> Tab: Type -> Filter layout -> new

**For Fields (e.g. Image)**

Overwrite:
1. Copy file: plugins/fieldsandfilterstypes/image/tmpl/field/default.php 
2. To: templates/your_template/html/plg_fieldsandfilterstypes_image/field/default.php

New:
1. Copy file: plugins/fieldsandfilterstypes/image/tmpl/field/default.php 
2. Rename file, eg.: plugins/fieldsandfilterstypes/image/tmpl/field/new.php
3. Go to PA -> Components -> Fields and Filters -> Fields -> your_field_name -> Tab: Type -> Field layout -> new

**For Static (e.g. Image)**

Overwrite:
1. Copy file: plugins/fieldsandfilterstypes/image/tmpl/static/default.php 
2. To: templates/your_template/html/plg_fieldsandfilterstypes_image/static/default.php

New:
1. Copy file: plugins/fieldsandfilterstypes/image/tmpl/static/default.php 
2. Rename file, eg.: plugins/fieldsandfilterstypes/image/tmpl/static/new.php
3. Go to PA -> Components -> Fields and Filters -> Fields -> your_field_name -> Tab: Type -> Field layout -> new

**Comment by tkulka** [comment]
> Or is ther a soulution to add dies Values from the Fields in a JSON-LD script?

**If you need render fields in php file, you can use helper for this.**

```
/*
* Get render fields
* $options e.g.: 'com_content'
* $itemID - article id
* $fieldsID - filed/fields id. You can put here integer/array
*/
$fields = FieldsandfiltersFieldsHelper::getFieldsLayoutsByItemID($option, $itemID, $fieldsID, true, '', new JRegistry(), 'id');

/*
* Display the rendered filed
* Display the field where has id: 10
*/
echo $fields->get(10);
```

Example:

```
$fields = FieldsandfiltersFieldsHelper::getFieldsLayoutsByItemID('com_content', 1, array(10, 11), true, '', new JRegistry(), 'id');

echo $fields->get(10);
echo $fields->get(11);
```

**If you need values article and field(s):**

```
/*
* Get values article and field(s)
* $options e.g.: 'com_content'
* $itemID - article id
* $fieldsID - filed/fields id. You can put here integer/array
*/
$item = FieldsandfiltersFieldsHelper::getFieldsByItemID($option, $itemID, $fieldsID);
```

Example:

```
$item = FieldsandfiltersFieldsHelper::getFieldsByItemID('com_content', 1, array(10, 11));
print_r($item->get('element')); // get values article
print_r($item->get('fields')); // get the fields that uses article
```

**Comment by Lovntola** [comment]
The Answer about was helpful.
