### ISSUE TITLE
editing fields and filters on frontend

### ISSUE THREAD

**Issue by nuketa** [fields-and-filters/fields-and-filters#6]
I am allowing my joomla users edit articles in the frontend but the fields and filters are not displayed. In the joomla administration site they are showing correctly.

Am I missing some configuration option?

Thanks.

(I'm using Joomla 3.4.5)

**Comment by tkulka** [comment]
Hello @nuketa,

First you need enable option, go to:
`PA -> Components -> Fields and Filters -> Plugin: Extensions -> [Fieldsandfilters] Content - Articles -> Tab: Fields -> Frontend edit: Yes.`

Next, you need [article edit layout](http://docs.joomla.org/Layout_Overrides_in_Joomla):
`components/com_content/views/form/tmpl/edit.php`

And add some code:
**For Joomla 3.x:**

```
<ul class="nav nav-tabs">
   ...
   <li><a href="#fieldsandfilters" data-toggle="tab"><?php echo JText::_('COM_FIELDSANDFILTERS') ?></a></li>
</ul>

<div class="tab-content">
   ...
    <div class="tab-pane" id="fieldsandfilters">
        <?php
            $this->set('fieldset', 'fieldsandfilters');
            echo JLayoutHelper::render('joomla.edit.fieldset', $this);
        ?>
    </div>
</div>
```

**For Joomla 2.5.x:**
Add this code before `</form>`:

```
<fieldset>
    <legend><?php echo JText::_('COM_FIELDSANDFILTERS'); ?></legend>
    <?php foreach ($this->form->getFieldset('fieldsandfilters') AS $field): ?>
        <?php echo $field->label; ?>
        <?php echo $field->input; ?>
    <?php endforeach; ?>
</fieldset>
```

**Comment by nuketa** [comment]
Thanks you! It works great! :-D.
